from PIL import Image

image = Image.open("lenna.jpg")
rgb_image = image.convert("RGB")
red, green, blue = rgb_image.split()
coordinates_red_1 = (100, 0, red.width, red.height)
cropped_red_1 = red.crop(coordinates_red_1)
coordinates_red_2 = (50, 0, red.width - 50, red.height)
cropped_red_2 = red.crop(coordinates_red_2)
red_blend = Image.blend(cropped_red_1, cropped_red_2, 0.5)
coordinates_blue_1 = (0, 0, blue.width - 100, blue.height)
cropped_blue_1 = blue.crop(coordinates_blue_1)
coordinates_blue_2 = (50, 0, blue.width - 50, blue.height)
cropped_blue_2 = blue.crop(coordinates_blue_2)
blue_blend = Image.blend(cropped_blue_1, cropped_blue_2, 0.5)
coordinates_green = (50, 0, green.width - 50, green.height)
cropped_green = green.crop(coordinates_green)
new_image_lenna = Image.merge("RGB", (red_blend, cropped_green, blue_blend))
new_image_lenna.save("new_image_lenna.jpg")
new_image_lenna.thumbnail((80, 80))
new_image_lenna.save("new_image_lenna_thumbnailed.jpg")